# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoDeletableWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoDeletableDialogWindow(object):
    def setupUi(self, NoDeletableDialogWindow):
        NoDeletableDialogWindow.setObjectName("NoDeletableDialogWindow")
        NoDeletableDialogWindow.resize(311, 66)
        self.horizontalLayout = QtWidgets.QHBoxLayout(NoDeletableDialogWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(NoDeletableDialogWindow)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NoDeletableDialogLabel1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NoDeletableDialogLabel1.setFont(font)
        self.NoDeletableDialogLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.NoDeletableDialogLabel1.setObjectName("NoDeletableDialogLabel1")
        self.verticalLayout.addWidget(self.NoDeletableDialogLabel1)
        self.NoDeletableDialogLabel2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NoDeletableDialogLabel2.setFont(font)
        self.NoDeletableDialogLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.NoDeletableDialogLabel2.setObjectName("NoDeletableDialogLabel2")
        self.verticalLayout.addWidget(self.NoDeletableDialogLabel2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(NoDeletableDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(NoDeletableDialogWindow)

    def retranslateUi(self, NoDeletableDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        NoDeletableDialogWindow.setWindowTitle(_translate("NoDeletableDialogWindow", "WARNING"))
        self.NoDeletableDialogLabel1.setText(_translate("NoDeletableDialogWindow", "Нельзя удалить этот элемент."))
        self.NoDeletableDialogLabel2.setText(_translate("NoDeletableDialogWindow", "Он используется в телефонной книге."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NoDeletableDialogWindow = QtWidgets.QDialog()
    ui = Ui_NoDeletableDialogWindow()
    ui.setupUi(NoDeletableDialogWindow)
    NoDeletableDialogWindow.show()
    sys.exit(app.exec_())
