# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoUniqueDialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoUniqueDialogWindow(object):
    def setupUi(self, NoUniqueDialogWindow):
        NoUniqueDialogWindow.setObjectName("NoUniqueDialogWindow")
        NoUniqueDialogWindow.resize(306, 64)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NoUniqueDialogWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(NoUniqueDialogWindow)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NoUniqueDialogLabel1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NoUniqueDialogLabel1.setFont(font)
        self.NoUniqueDialogLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.NoUniqueDialogLabel1.setObjectName("NoUniqueDialogLabel1")
        self.verticalLayout.addWidget(self.NoUniqueDialogLabel1)
        self.NoUniqueDialogLabel2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NoUniqueDialogLabel2.setFont(font)
        self.NoUniqueDialogLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.NoUniqueDialogLabel2.setObjectName("NoUniqueDialogLabel2")
        self.verticalLayout.addWidget(self.NoUniqueDialogLabel2)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(NoUniqueDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(NoUniqueDialogWindow)

    def retranslateUi(self, NoUniqueDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        NoUniqueDialogWindow.setWindowTitle(_translate("NoUniqueDialogWindow", "WARNING"))
        self.NoUniqueDialogLabel1.setText(_translate("NoUniqueDialogWindow", "Нельзя добавить этот элемент."))
        self.NoUniqueDialogLabel2.setText(_translate("NoUniqueDialogWindow", "Такой элемент уже есть в таблице."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NoUniqueDialogWindow = QtWidgets.QDialog()
    ui = Ui_NoUniqueDialogWindow()
    ui.setupUi(NoUniqueDialogWindow)
    NoUniqueDialogWindow.show()
    sys.exit(app.exec_())
